fiass_db:
  collection_name: "document_portal"

embedding_model:
  huggingface:
    model_name: "all-MiniLM-L6-v2"
    type: "sentence-transformers"
    provider: "huggingface"

  google:
    provider: "google"
    model_name: "gemini-embedding-001"


retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0.0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.5-flash"

  openai:
    provider: "openai"
    model_name: "gpt-4o"
    temperature: 0.0
    max_output_tokens: 2048

